<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Siti Innaya Rahmani Sitepu">
<meta name="dcterms.date" content="2023-01-19">

<title>Analisis Pengaruh Export Terhadap PDB Indonesia pada tahun 2017-2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Export Terhadap PDB Indonesia pada tahun 2017-2021</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Siti Innaya Rahmani Sitepu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 19, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Produk domestik bruto atau yang biasa disebut PDB, merupakan total nilai moneter dari semua barang dan jasa akhir yang diproduksi dan dijual di pasar di suatu negara selama periode waktu tertentu biasanya 1 tahun. PDB yang disebut juga GDP atau Gross Domestic Product digunakan untuk untuk mengukur kesehatan ekonomi suatu negara. PBD yang tinggi menggambarkan bagaimana gambaran perekonomian serta sumber daya ekonomi yang besar. PDB suatu negara yang memiliki nilai yang besar, menggambarkan bagaimana tingkat produksi yang cukup tinggi yang nantinya akan berpengaruh kepada tingkat daya beli masyarakat.</p>
<p>Perhitungan besar kecilnya PDB dipengaruhi oleh beberapa faktor, antara lain: konsumsi rumah tangga (C), investasi (I), pengeluaran pemerintah (G), dan net ekspor yang dikurangi dengan impor (X-M). Ekspor menjadi salah satu jalan bagi suatu negara untuk meningkatkan nilai PDB nya. Hal ini dikarnakan ekspor akan secara langsung memberi kenaikan penerimaan dalam pendapatan suatu negara. Terjadinya kenaikan penerimaan pendapatan suatu negara akan mengakibatkan terjadinya kenaikan tingkat PDB. Dengan kata lain ekspor akan menyebabkan pertumbuhan ekonomi.</p>
<p>Didalam kegiatan perdagangan internasional, ekspor merupakan salah satu jalan yang sangat penting untuk meningkatkan pertumbuhan ekonomi karna berdampak besar bagi negara maupun masyarakatnya. Aktivitas ekspor memberikan keuntungan bagi suatu negara untuk meningkatkan devisa serta membuka lapangan pekerjaan dan meningkatkan daya saing masyarkatnya dalam perdagangan. Ekspor menjadi salah satu aspek paling penting bagi suatu negara, hal ini karnakan ekspor dapat bekerja secara luas di berbagai negara yang dapat berdampak pada peningkatan jumlah produksi yang mendorong pertumbuhan ekonomi sehingga diharapkan dapat memberikan kontribusi yang besar terhadap pertumbuhan dan stabilitas perekonomian negara.</p>
<p>Negara Indonesia merupakan negara pengekspor bahan pangan dan bahan produksi karena kekayaan alam negeri ini melimpah sehingga mampu menyambut peluang bisnis berskala internasional. Dalam rentang tahun 2017 hingga 2021, ekspor indonesia rata rata meningkat. Menurut data BPS, pada tahun 2017 nilai ekspor Indonesia mencapai 168.828,2 juta dolar AS, mengalami peningkatan yang cukup signifikan jika dibandingkan tahun 2016 sebesar 16,28 persen. Kemudian, ditahun 2018 ekspor pun meningkat senilai nilai ekspor Indonesia mencapai 180.012,7 juta dolar AS, mengalami peningkatan yang cukup signifikan jika dibandingkan tahun 2017 sebesar 6,62 persen.</p>
<p>Sementara, ditahun 2019 nilai ekspor Indonesia mencapai 167.683,0 juta dolar AS, mengalami penurunan yang cukup signifikan jika dibandingkan tahun 2018 sebesar 6,85 persen dikarnakan pembatasan yang diberlakukan disebabkan Covid-19. Pada tahun 2020 dan 2021, Indonesia mulai membangun kinerja baru pasca menyebarnya Covid-19, sehingga kinerja ekspor tetap meningkat senilai US$ 67,38 miliar, naik sebesar 24,96% dibandingkan periode yang sama di tahun sebelumnya. Peningkatan kinerja ekspor tersebut dipicu oleh peningkatan nilai ekspor produk migas sebesar 27,14% dan produk non migas sebesar 24,84%. Meskipun, secara keseluruhan rata rata eskpor mengalami kenaikan, kenaikan ini memberikan distribusi pada PDB Indonesia dalam rentang tahun 2017 hingga 2021.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Ruang lingkup penelitian ini adalah kenaikan PDB yang dipengaruhi oleh ekspor, khususnya ditahun 2017 hingga 2021 di Indonesia. Bagaimana ekspor mulai menyumbangkan kinerja nya untuk meningkatkan nilai PDB di Indonesia yang mulai menjalin transaksi perdagangan internasional ditahun 2021 pasca Covid-19 yang melanda seluruh dunia dan memberikan dampak khususnya pada sektor perekonomian. Penelitian ini mengerucutkan ruang lingkup, yaitu hanya ditahun 2017 hingga 2021 saja serta hanya pada indikator ekspor yang berada di Indonesia saja. Pembahasan didalam analisis ” Pengaruh Ekspor Terhadap Produk Domestik Bruto Indonesia ditahun 2017 hingga 2021” dirancang untuk melihat tranansaksi ekspor baik barang maupun jasa dan apakah ekspor yang meningkat berjalan seiringan dengan kenaikan PDB diIndonesia.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li><p>Bagaimana transaksi ekspor secara keseluruhan dalam rentang 5 tahun terakhir?</p></li>
<li><p>Apakah jika terjadi kenaikan ekspor ini berjalan seiringan dengan PDB?</p></li>
<li><p>Apakah ekspor yang meningkat ini memberikan kontribusi terhadap kenaikan pertumbuhan PDB dalam rentang tahun 2017 hingga 2021?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>penelitian ini dapat digunakan untuk membantu peneliti dalam menganalisi pengaruh ekspor terhadap PDB Indonesia.Adapun tujuan yang ingin dicapai melihat rumusan masalah yang telah dipaparkan sebelumnya, maka tujuan dari penelitian adalah :</p>
<ol type="1">
<li><p>Untuk mengetahui transaksi ekspor secara keseluruhan dalam rentang 5 tahun terakhir?</p></li>
<li><p>Untuk mengetahui dan menganalisis kenaikan ekspor berjalan dengan PDB.</p></li>
<li><p>Untuk mengetahu ekspor yang meningkat ini memberikan kontribusi terhadap kenaikan pertumbuhan PDB dalam rentang tahun 2017 hingga 2021.</p></li>
</ol>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>dalam melakukan analisis “Pengaruh Ekspor Terhadap PDB Indonesia ditahun 2017 - 2021”, beberapa pacakage yang digunakan dalam aplikasi Rstudio adalah:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>Ekspor</strong></p>
<p>Ekspor adalah salah satu cara untuk melakukan penjualan komoditi yang dimiliki kepada bangsa lain atau negara asing dengan mengkuti ketentuan pemerintah dengan mengharapkan pembayaran yang nantinya akan memberikan Imbal hasil yang diperoleh dari kegiatan mengekspor yang berdampak pada peningkatan nilai sejumlah atau biasa disebut dengan istilah devisa yang digunakan sebagai salah satu sumber pemasukan negara. Eksporjuga disebut dengan kegiatan perdagangan yang memberikan rangsangan guna menumbuhkan permintaan dalam negeri yang menyebabkan timbulnya industri-industri pabrik besar, bersamaan dengan struktur politik yang stabil dan lembaga sosial yang efisien (Todaro,2006). Ekspor akan memberikan efek yang positif ke atas kegiatan ekonomi negara, karena ia merupakan pengeluaran penduduk negara lain ke atas barang-barang yang dihasilkan dalam negeri.</p>
<p><strong>Pertumbuhan Ekonomi</strong></p>
<p>Kemampuan suatu negara untuk menyediakan semakin banyak jenis barang-barang ekonomi kepada penduduknya disebut dengan pertumbuhan ekonomi. Kemampuan suatu negara ini tumbuh sesuai dengan penyesuaian kelembagaan dan ideologis yang diperlukan negara, kemampuan suatu negara ini juga tumbuh karena kemajuan teknologi (Jhingan, 2000).Setiap negara akan menambah produksi barang dan jasa disetiap periode karena pertumbuhan ekonomi adalah masalah makro ekonomi dalam jangka panjang. Kesejahteraan ekonomi yang meningkat ditandai dengan pertumbuhan ekonomi yang tinggi dan stabil dari tahun ke tahun berikutnya. Pertumbuhan ekonomi disisi lain juga digunakan untuk melihat tepat atau tidaknya kebijakan pemerintah.</p>
<p><strong>Hubungan Antara Ekspor Dengan Produk Domestik Bruto</strong></p>
<p>Faktor penting untuk merangsang pertumbuhan ekonomi disuatu negara adalah ekspor. Dengan adanya ekspor disuatu negara maka kapasitas konsumsi akan membesar serta output dunia akan meningkat, pasar internasional dengan berbagai produk ekspor yang langka pun bisa tersajikan. Negara miskin tidak akan mampu untuk meningkatkan perekonomian nasional tanpa adanya ekspor. Keuntungan dari skala ekonomi pun bisa diambil setiap negara yang melakukan ekspor. Suatu negara akan memperoleh keuntungan dan pendapatan nasional suatu negara naik apabila negara yang bersangkutan melakukan ekspor dan hal ini termasuk dalam fungsi penting komponen ekspor dari perdagangan luar negeri yang pada gilirannya menaikkan jumlah output dan laju pertumbuhan ekonomi. Garis kemiskinan pun bisa dipatahkan karena dengan tingginya tingkat output dan pembangunan ekonomi dapat terus menerus ditingkatkan (Jhingan, 2000).</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>negara</th>
<th>Tahun</th>
<th>PDB</th>
<th>Export</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Indonesia</td>
<td>2017</td>
<td>27.64652</td>
<td>26.04591</td>
</tr>
<tr class="even">
<td>Indonesia</td>
<td>2018</td>
<td>27.67242</td>
<td>26.11191</td>
</tr>
<tr class="odd">
<td>Indonesia</td>
<td>2019</td>
<td>27.74355</td>
<td>26.06108</td>
</tr>
<tr class="even">
<td>Indonesia</td>
<td>2020</td>
<td>27.68805</td>
<td>25.93194</td>
</tr>
<tr class="odd">
<td>Indonesia</td>
<td>2021</td>
<td>27.80169</td>
<td>26.26739</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan sumber data <strong>World Development Indicator (WDI)</strong>, dengan menggunakan data sekunder yang kemudian diolah dengan melakukan log pada kedua variabel untuk memudahkan analisis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readxl' was built under R version 4.2.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/usee/Documents/METOPEL UAS/FILEUASMETOPEL"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"regresi.xlsx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(LPDB<span class="sc">~</span>Lexport,<span class="at">data=</span>dat)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LPDB ~ Lexport, data = dat)

Residuals:
       1        2        3        4        5 
-0.05077 -0.04788  0.04097  0.03051  0.02716 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  18.6142     5.5958   3.326   0.0448 *
Lexport       0.3487     0.2145   1.626   0.2025  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.05233 on 3 degrees of freedom
Multiple R-squared:  0.4683,    Adjusted R-squared:  0.2911 
F-statistic: 2.642 on 1 and 3 DF,  p-value: 0.2025</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>LPDB<span class="sc">~</span>dat<span class="sc">$</span>export,<span class="at">ylab=</span><span class="st">"PDB"</span>,<span class="at">xlab=</span><span class="st">"Export"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/ggplot%20Indonesia%205%20tahun-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">ggplot data visual export dengan PDB Indonesia 2017-2021</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini merbaksud mencari hubungan antara export dan PDB. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_i+\mu_i
\]</span> di mana <span class="math inline">\(y_i\)</span> adalah Export dan <span class="math inline">\(x_i\)</span> adalah PDB.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>negara</th>
<th>Tahun</th>
<th>PDB</th>
<th>Export</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Indonesia</td>
<td>2017</td>
<td>27.64652</td>
<td>26.04591</td>
</tr>
<tr class="even">
<td>Indonesia</td>
<td>2018</td>
<td>27.67242</td>
<td>26.11191</td>
</tr>
<tr class="odd">
<td>Indonesia</td>
<td>2019</td>
<td>27.74355</td>
<td>26.06108</td>
</tr>
<tr class="even">
<td>Indonesia</td>
<td>2020</td>
<td>27.68805</td>
<td>25.93194</td>
</tr>
<tr class="odd">
<td>Indonesia</td>
<td>2021</td>
<td>27.80169</td>
<td>26.26739</td>
</tr>
</tbody>
</table>
<p>Berdasarkan data dapat dilihat bahwa volume PDB dan Ekspor di Indonesia berjalan searah dalam rentang tahun 2017 hingga 2021. Ditahun 2018, nilai PDB berada di angka 27.67242 dengan nilai export sebanyak 26.04591. nilai ini lebih tinggi dibandingkan tahun 2017, dengan nilai PDB 27.64652 dengan angka ekspor 26.04591.Ini artinya ditahun 2017 dan 2018 ekspor dan PDB berjalan searah dalam kenaikannya atau dapat dikatakan export mempengaruhi kenaikan PDB. Kemudian, ditahun 2019 ketika covid-19 awal melanda China, PDB Indonesia tetap mengalami peningkatan sebanyak 27.74355 tetapi Ekspor mengalami penurunan menjadi 26.06108 dikarnakan pembatasan yang mulai diberlakukan. Ditahun 2020, Tingkat PDB menurun menjadi 27.68805 dengan tingkat ekspor juga menurun menjadi 25.93194. ditahun terakhir, yaitu 2021 total pendapatan PDB Indonesia mengalami perbaikan sebanyak 27.80169 dengan total ekspor juga meningkat dibanding tahun sebelumnya menjadi 26.2626739</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(LPDB<span class="sc">~</span>Lexport,<span class="at">data=</span>dat)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LPDB ~ Lexport, data = dat)

Residuals:
       1        2        3        4        5 
-0.05077 -0.04788  0.04097  0.03051  0.02716 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  18.6142     5.5958   3.326   0.0448 *
Lexport       0.3487     0.2145   1.626   0.2025  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.05233 on 3 degrees of freedom
Multiple R-squared:  0.4683,    Adjusted R-squared:  0.2911 
F-statistic: 2.642 on 1 and 3 DF,  p-value: 0.2025</code></pre>
</div>
</div>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>berdasarkan hasil analisis, maka dapat dismpulkan bahwa transaksi ekspor indonesia secara keseluruhan dari tahun 2017 hingga 2021 mengalami kenaikan, terkecuali di tahun 2020 dikarnakan mulai berlakunya pembatasan covid-19. kemudian kenaikan ekspor di indonesia berjalan seiringan dengan PDB Indonesia begitu juga dengan penurunan ditahun 2020. Serta ekspor memberikan kontribusi pada PDB Indonesia tetapi tidak signifikan, dengan nilai 5%</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Asbiantari, D. R., Hutagaol, M. P., &amp; Asmara, A. (2016). Pengaruh ekspor terhadap pertumbuhan ekonomi Indonesia. Jurnal Ekonomi dan Kebijakan Pembangunan, 5(2), 10-31.</p>
<p>Astuti, I. P., &amp; Ayuningtyas, F. J. (2018). Pengaruh ekspor dan impor terhadap pertumbuhan ekonomi di Indonesia. Jurnal Ekonomi &amp; Studi Pembangunan, 19(1), 1-10.</p>
<p>Febriyanti, D. F. (2019). Effect of Export and Import of Gross Domestic Product in Indonesia 2008-2017. Jurnal Ecoplan, 2(1), 10-20.</p>
<p>Hodijah, S., &amp; Angelina, G. P. (2021). Analisis pengaruh ekspor dan impor terhadap pertumbuhan ekonomi di Indonesia. Jurnal Manajemen Terapan dan Keuangan, 10(01), 53-62.</p>
<p>Maharani, A. (2022, September 26). PENGARUH EKSPOR, IMPOR DAN GDP DALAM PERTUMBUHAN EKONOMI DI NEGARA BAHRAIN DAN KWAIT. https://doi.org/10.31219/osf.io/ztduc</p>
<p>Siregar, I. M., Pratiwi, I., Nurhasanah, N., &amp; Sinaga, S. (2019). Pengaruh Ekspor Terhadap Pertumbuhan Ekonomi Di Indonesia Periode Tahun 2013-2017. Jurnal Ekodik: Ekonomi Pendidikan, 7(2), 46-54.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>